### Endpoints Públicos (no requieren autenticación JWT)

##Crear usuario
# Este endpoint crea un nuevo usuario en el sistema.
# Al crearse, se le asigna automáticamente un único rol por defecto (ej: ROLE_USER).
# No requiere token.
POST http://localhost:8080/v1/public/users/create
Content-Type: application/json

{
  "documento": 2,
  "nombre": "Carlos Ramírez",
  "email": "user@gmail.com",
  "password": "123",
  "fechaNacimiento": "1990-01-01",
  "genero": "Alien"
}

###Listar Trabajos
GET http://localhost:8080/v1/public/all-jobs
Accept: application/json

### Login usuario
# Este endpoint autentica al usuario y devuelve un JWT.
# Con este token podrás acceder a los endpoints protegidos.
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password":"123"
}