###Endpoints para rol USUARIO (requiere JWT con rol = ROLE_USER)

# Este endpoint permite a un usuario autenticado crear un nuevo trabajo
# con descripción, pago, ubicación y categoría.
# IMPORTANTE: Requiere agregar el token en Authorization: Bearer <jwt>
POST http://localhost:8080/v1/jobs/create
Content-Type: application/json
Authorization: Bearer

{
  "titulo": "Instalacion de Software",
  "descripcion": "Se requiere asesoria con la descarga de DockerDesktop.",
  "pago": 50000.0,
  "tipoPago": "Efectivo",
  "ubicacion": "PALMAS",
  "categoria": "ASESORIAS"
}

###Este endpoint permite al usuario autenticado registrarse a un trabajo específico
# IMPORTANTE: Requiere agregar el token en Authorization: Bearer <jwt>
#También se debe reemplazar {jobId} con el ID del trabajo al que se desea registrar
PATCH http://localhost:8080/v1/jobs/take-job/{jobId}
Authorization: Bearer

###Este endpoint permite al ususario solicitante eliminar sus propios trabajos
# IMPORTANTE: Requiere agregar el token en Authorization: Bearer <jwt>
#También se debe reemplazar {jobId} con el ID del trabajo al que se desea eliminar
DELETE http://localhost:8080/v1/jobs/published/delete/{jobId}
Authorization: Bearer

###Este enpoint permite al usuario autenticado ver todos los trabajos que ha creado
# IMPORTANTE: Requiere agregar el token en Authorization: Bearer <jwt>
GET http://localhost:8080/v1/jobs/posted-by-me
Accept: application/json
Authorization: Bearer

####Este endpoint permite al usuario autenticado ver todos los trabajos a los que se ha registrado
# IMPORTANTE: Requiere agregar el token en Authorization: Bearer <jwt>
GET http://localhost:8080/v1/jobs/worked-by-me
Accept: application/json
Authorization: Bearer 
