###Endpoints para rol USUARIO (requiere JWT con rol = ROLE_USER)

# Este endpoint permite a un usuario autenticado crear un nuevo trabajo
# con descripción, pago, ubicación y categoría.
# IMPORTANTE: Requiere agregar el token en Authorization: Bearer <jwt>
POST http://localhost:8080/v1/jobs/create
Content-Type: application/json
Authorization: Bearer

{
  "descripcion": "Instalación de software.",
  "pago": 150.0,
  "ubicacion": "Bogotá, Colombia",
  "categoria": "OTRO"
}