# Configuracion de la base de datos para el perfil prod
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USERNAME}
spring.datasource.password=${BD_PASSWORD}

# Configuracion especifica para PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true

##Flyway desactivado mientras desarrollamos
spring.flyway.enabled=false

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

##Health check
management.endpoints.web.base-path=/internal
management.endpoint.health.show-details=always